### PR TITLE
Issue #12: Clean up module name and description.

### PR DESCRIPTION
**Pull request by jenlampton**
Fixes https://github.com/backdrop-contrib/auto_nodetitle/issues/12

### CODE REVIEW

**Comment by klonos** [comment]
I'm pretty sure we ~~use Camel case for~~ capitalize project names, so it should be "Automatic **N**ode **T**itles" instead (it also helps avoid confusion when we are referring to the module in documentation since capital letters for the words "node" and "title" make it clear that we are referring to a specific thing and not Drupal/Backdrop lingo).

**Comment by klonos** [comment]
It's correct on the repo description:

auto_nodetitle-proper_capitalization

**Comment by jenlampton** [comment]
@klonos We actually use Sentence case for project names. It was what earlier versions of Drupal did for all strings all throughout core because every other way of capitalization can be done with CSS, but Sentence case can't. 

I'm not entirely sure how I feel about that (I prefer Proper Name Case myself) but that's what we do.

**Comment by klonos** [comment]
> We actually use Sentence case for project names. It was what Drupal did...

Hmm, nope:

> **name (Required)**
> This displays the name of your module, which will appear on the Modules page. Since module names are proper names, it should be capitalized as a proper name (e.g., "Really Neat Widget", not "really neat widget" or "Really neat widget"), and it should be a human-readable name (not really_neat_widget). If your module name includes an acronym (CSS, WYSIWYG, UI, etc.) or a third-party trade name (jQuery, JavaScript), of course follow the standard capitalization for those.
> `name = Really Neat Widget`

(source: [Writing module .info files (Drupal 7.x)](https://www.drupal.org/node/542202#name))

The coding standard was decided in [Decide on coding standard for capitalization of module names [policy, no patch] [#1346158]](https://www.drupal.org/node/1346158)

I have to admit that technically I was not 100% correct either (always confuse Proper Case/Title Case with [CamelCase](https://en.wikipedia.org/wiki/CamelCase)). Point still the same though: the module name should be "Automatic **N**ode **T**itles".

**Comment by jenlampton** [comment]
Those are Drupal 8's standards ;)

**Comment by jenlampton** [comment]
@klonos I don't think we really have a strong feeling on this one way or the other. If you feel strongly that we should adopt Proper Name Case like Drupal 8 did, then let's do it.  Please open an issue against Backdrop Core so we can get those all fixed up (if they aren't already), and let's find somewhere to document it.

Since this issue has already been merged, please open a new one here as well :)

**Comment by klonos** [comment]
Done! :wink:

Sorry about bringing this up here, but I feel that once the policy is decided, you might need to revert changes. That's all.

**Comment by jenlampton** [comment]
> but I feel that once the policy is decided, you might need to revert changes. That's all.

Fair enough! :)

**Pull request merged**
